### ISSUE TITLE
dependabotを設定する

### ISSUE THREAD

**Issue by sho-h** [matsuerb/maze_solver_collector#6]
maze_solver_collectorはOSSなので、[dependabot](https://dependabot.com)が無料で使えます。gemパッケージの更新は自動化して、単体テストで問題が出たら実際に見てみるくらいでいいかもしれません。

**Comment by nishidayuya** [comment]
自分の個人リポジトリで使ってみました．Dependabot便利ですね．賛成です．

Organizationのアクセス許可が必要で自分のアカウントだと [Dependabot · GitHub Marketplace](https://github.com/marketplace/dependabot) から設定できませんでした．

他，以下を確認しました．

* nishidayuya/maze_solver_collectorに設定できた．
* 自分がOwnerのテスト用Organizationを作ったところ設定できた．

**Comment by nishidayuya** [comment]
松江Ruby会議08も終わってこのリポジトリはもうメンテナンスしないため，本リポジトリは #11 でread only化します．
